language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma-cli
  - bower install

env:
  - CHROME_BIN

script:
  - gulp test
